server:
    port: 8080

spring:
    thymeleaf:
        cache: false
        check-template-location: true
        content-type: text/html
        encoding: UTF-8
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html

haoweilai:
    accesskey: xxxxxxxx
    accessSecret: xxxxxx
